                </div>
                    <div class="text-center" style="background-color: #abf2a0a9; margin:1%; padding: 1%;">La carne de cerdo, carne de chancho, carne de puerco, carne de marrano, carne de cochino, o simplemente cerdo, chancho, cochino, marrano, cerdo americano, es un producto cárnico procedente del cerdo.</div>
                    <div class="text-center" style="margin: 1%;">
                      <button id="liveToastBtn20" type="button" class="btn btn-danger "  marcador="20">Agregar 🛒</button>
                      <div class="position-fixed bottom-0 start-0 p-3" style="z-index: 11">
                        <div id="liveToast20" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                          <div class="toast-header">
                            <img src="./IMG/mercado.png" class="rounded me-2" alt="...">
                            <strong class="me-auto">CARRITO</strong>
                            <small>Hace 1 segundo</small>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                          </div>
                          <div class="toast-body">
                            Su producto fue agregado a el carrito
                          </div>
                        </div>
                      </div>
                    </div>
                    
                  </div>
                </div>
                <div class="accordion-item"  style="margin-bottom: 3px;">
                  <h2 class="accordion-header" id="flush-headingThree" style="border: #88ec79 solid 2px;">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree" style="background-color: #ABF2A0;">
                      MUSLOS DE POLLO <img src="./IMG/pollo.png" alt="">
                    </button>
                  </h2>
                  <div id="flush-collapseThree" class=